# Generated by Django 5.1.5 on 2025-01-24 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact_connected_contact_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 24, 13, 34, 15, 445326, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
