# Generated by Django 5.1.5 on 2025-01-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
